name: CI
on:
  push:
    branches:
      - master
  pull_request:
  # see: https://github.com/dependabot/dependabot-core/issues/3253#issuecomment-797125425
  pull_request_target:
env:
  CMS_API_URL: ${{ secrets.CMS_API_URL }}
  CMS_API_TOKEN: ${{ secrets.CMS_API_TOKEN }}

jobs:
  type-check:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    if: |
      (github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]') ||
      (github.event_name != 'pull_request_target' && github.actor != 'dependabot[bot]')
    steps:
      - name: Checkout
        if: ${{ github.event_name != 'pull_request_target' }}
        uses: actions/checkout@v2
      - name: Checkout PR
        if: ${{ github.event_name == 'pull_request_target' }}
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Display version of Node.js, npm, yarn
        run: |
          node -v
          npm -v
          yarn --version
      - run: yarn
      - run: yarn type-check

  lint:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    if: |
      (github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]') ||
      (github.event_name != 'pull_request_target' && github.actor != 'dependabot[bot]')
    steps:
      - name: Checkout
        if: ${{ github.event_name != 'pull_request_target' }}
        uses: actions/checkout@v2
      - name: Checkout PR
        if: ${{ github.event_name == 'pull_request_target' }}
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Display version of Node.js, npm, yarn
        run: |
          node -v
          npm -v
          yarn --version
      - run: yarn
      - run: yarn lint
