name: main CI
on:
  push:
    branches:
      - master
    paths:
      - 'content/**.md'

jobs:
  tweet:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: get-text
        run: |
          text=$(git diff-tree -m --no-commit-id --name-status -r HEAD | grep '^A.*\.md$' | sed -r "s/^.+\/(.+).md\$/ブログ投稿ーー！ https:\/\/markey-dev.com\/posts\/\1/")
          echo "::set-output name=text::$text"
      - if: env.TWITTER_TEXT != ''
        uses: snow-actions/tweet@v1.2.0
        with:
          status: ${{ env.TEXT }}
        env:
          TEXT: ${{ steps.get-text.outputs.text }}
          CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          CONSUMER_API_SECRET_KEY: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
