name: Deployment Status
on: [deployment_status]

jobs:
  tweet:
    # run only main branch
    if: github.event.deployment_status.state == 'success' && github.event.deployment.environment == 'Production'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: get-text
        run: |
          text=$(git diff-tree -m --no-commit-id --name-status -r HEAD | grep '^A.*content\/.*\.md$' | sed -r "s/^.+\/(.+)\.md\$/書いたよ https:\/\/markey-dev.com\/posts\/\1/")
          echo "::set-output name=text::$text"
      - if: env.TEXT != ''
        uses: snow-actions/tweet@v1.2.0
        with:
          status: ${{ env.TEXT }}
        env:
          TEXT: ${{ steps.get-text.outputs.text }}
          CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          CONSUMER_API_SECRET_KEY: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
