name: main CI
on:
  push:
    branches:
      - master
    paths:
      - 'content/**.md'

jobs:
  tweet:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
      - run: gem install twurl
      - id: get-text
        name: Get Text
        run: |
          text=$(git diff-tree -m --no-commit-id --name-status -r HEAD | grep '^A.*\.md$' | sed -r "s/^.+\/(.+).md\$/ブログ投稿ーー！ https:\/\/markey-dev.com\/posts\/\1/")
          echo "::set-output name=text::$text"
      - if: env.TWITTER_TEXT != ''
        run: |
          twurl authorize --bearer --consumer-key $TWITTER_CONSUMER_KEY --consumer-secret $TWITTER_CONSUMER_SECRET
          ls -l ~/.twurlrc
          twurl -t --bearer --consumer-key $TWITTER_CONSUMER_KEY -d "status=$TWITTER_TEXT" /1.1/statuses/update.json
        env:
          TWITTER_TEXT: ${{ steps.get-text.outputs.text }}
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
