name: main CI
on:
  push:
    branches:
      - master

jobs:
  tweet:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Get Status
        run: git log -m -1 --name-status --pretty="format:" $GITHUB_SHA | grep '^A.*\.md$' | sed -r "s/^.+\/(.+).md\$/ブログ投稿ーー！ https:\/\/markey-dev.com\/posts\/\1/"
